JD_KEYWORDS = {
    "retrieval": 10,
    "ranking": 10,
    "embeddings": 10,
    "vector": 8,
    "search": 8,
    "nlp": 8,
    "llm": 8,
    "python": 8,
    "milvus": 6,
    "qdrant": 6,
    "pinecone": 6,
    "faiss": 6,
    "weaviate": 6,
    "evaluation": 8,
    "ndcg": 8,
    "mrr": 8,
    "map": 8,
    "fine-tuning": 6,
    "lora": 6,
    "peft": 6,
    "rag": 8,
}
